- .gitignore
- modal-go/app.go
- modal-go/client.go
- modal-go/errors.go
- modal-go/function.go
- modal-go/image.go
- modal-go/proto/modal_proto/api.pb.go
- modal-go/proto/modal_proto/api_grpc.pb.go
- modal-go/proto/modal_proto/options.pb.go
- modal-go/sandbox.go
- modal-go/scripts/gen-proto.sh
- modal-go/test/function_test.go
- Poll in loop if it takes >55 seconds
- Handle errors in function results, add specific error struct definitions to Go
- Rename `proto` to `pb` so it doesn't conflict with `google/protobuf`
- Fix `FinalInput: true` stopping the container
> Full unary function call support for Go

- CHANGELOG.md
- modal-go/function.go
- modal-go/test/function_test.go
- modal-js/src/function.ts
- modal-js/test/function.test.ts
- modal-js/vitest.config.ts
- test-support/libmodal_test_support.py
In previous versions of libmodal, we did not support inputs greater than 2 MiB. This returned an error from the server. This PR adds support for inputs larger than 2 MiB via S3 offload.
```
FAIL  test/function.test.ts > FunctionCallLargeInput
ClientError: /modal.client.ModalClient/FunctionMap INVALID_ARGUMENT: The size of input 0 is 2.00MiB, which exceeds the maximum allowed size of 2.00MiB. Please reduce the size of the input and try again.
```
Multipart blob upload for calling functions is still not supported yet. This is currently set on the server for inputs greater than 128 MiB.
Also starting a changelog with this commit. Will probably bump modal-js to v0.3.3 and modal-go to v0.0.4 after this. It's backwards-compatible, modal-go is pretty unstable though so we don't have a patch …
> Support blob upload for calling functions

- .gitignore
- modal-go/cls.go
- modal-go/function.go
- modal-go/test/cls_test.go
- test-support/libmodal_test_support.py
Adds support for looking up Modal Cls and invoking its methods. 
```go
// Lookup class
cls, _ := modal.ClsLookup(
context.Background(),
"libmodal-test-support", "EchoClsParametrized", modal.LookupOptions{},
)
instance, _ := cls.Instance(map[string]any{"name": "hello-init"})
// Call method
function, _ = instance.Method("echo_parameter")
result, _ = function.Remote(context.Background(), nil, nil)
```
The interface `Methods map[string]*Function` is inelegant in Go but natural to Pythonistas. Open to ideas on how to make this better.
> Implements Cls lookups in Go

- modal-go/client.go
- modal-go/proto/modal_proto/api.pb.go
- modal-go/proto/modal_proto/api_grpc.pb.go
- modal-js/src/client.ts
It's not permanently going to be reporting at "1.0.0" exactly, just bumping it so it's off the `0.` prefix.
> Bump reported client version to 1.0.0

- README.md
- modal-js/src/app.ts
This is for consistency with our other JS APIs, and the ecosystem in general.
> Change sandbox timeout in JS to milliseconds

- README.md
- modal-go/cls.go
- modal-go/examples/cls-call/main.go
- modal-go/examples/function-call/main.go
- modal-go/examples/function-spawn/main.go
- modal-go/examples/sandbox-exec/main.go
- modal-go/examples/sandbox/main.go
- modal-go/function.go
- modal-go/function_call.go
- modal-go/test/function_call_test.go
- modal-go/test/sandbox_test.go
- modal-js/package.json
- modal-js/src/function.ts
- modal-js/src/function_call.ts
- modal-js/src/index.ts
- modal-js/test/function_call.test.ts
- modal-js/vitest.config.ts
- test-support/libmodal_test_support.py
Some follow-ups here, the main behavior change was that:
- `timeout` should be undefined by default rather than `55`, which waits indefinitely.
- `timeout` when set to 0 should poll once with an immediate timeout, not wait for `55` seconds.
Added tests for this. Also edited the Go examples with the feedback about `%v` vs `%w`, I can install a linter so we don't need to manually follow-up with things like this.
> Follow-ups to #12 Function.spawn in Go and TS

- modal-js/src/app.ts
We fielded a question from a user about units. This will show up in user IDEs to explain what the options do, and they'll also appear in the generated typedoc https://modal-labs.github.io/libmodal/types/SandboxCreateOptions.html
> Add docstrings to modal-js SandboxCreateOptions

- modal-go/app.go
- modal-go/errors.go
- modal-go/function.go
- modal-go/queue.go
- modal-go/test/queue_test.go
- modal-js/src/queue.ts
- modal-js/test/queue.test.ts
Uses the new `iter.Seq2` type with `range` loops in Go 1.23.
```go
for item, err := range queue.Iterate(nil) {
if err != nil {
panic(err)
}
fmt.Println(item)
}
```
> Implement Queue support for Go

- CHANGELOG.md
- README.md
- modal-go/app.go
- modal-go/config.go
- modal-go/examples/sandbox-private-image/main.go
- modal-go/image.go
- modal-go/secret.go
- modal-go/test/image_test.go
- modal-go/test/secret_test.go
- modal-js/eslint.config.js
- modal-js/examples/sandbox-private-image.ts
- modal-js/package.json
- modal-js/src/app.ts
- modal-js/src/client.ts
- modal-js/src/cls.ts
- modal-js/src/config.ts
- modal-js/src/function.ts
- modal-js/src/image.ts
- modal-js/src/index.ts
- modal-js/src/pickle.test.ts
- modal-js/src/queue.ts
- modal-js/src/sandbox.ts
- modal-js/src/secret.ts
- modal-js/test/image.test.ts
- modal-js/test/secret.test.ts
- modal-js/tsconfig.json
CLI-433
Adds support similar to [modal.Image.from_aws_ecr()](https://modal.com/docs/reference/modal.Image#from_aws_ecr), related support for `Secret`s.
> Add support for reading images from AWS ECR

- .github/workflows/ci.yaml
- modal-go/app.go
- modal-go/config.go
- modal-go/examples/sandbox-private-image/main.go
- modal-go/test/image_test.go
- modal-go/test/secret_test.go
- modal-js/examples/sandbox-private-image.ts
- modal-js/test/image.test.ts
- modal-js/test/secret.test.ts
- test-support/README.md
- test-support/setup.sh
This PR makes two changes:
1. Adds `test-support/setup.sh` that creates the test support fixtures programmatically and in the current environment. This scripts the process of creating test supports so they don't reference secrets in a specific environment that could be lost, allowing us to run tests against e.g., dev-clustser, and also documents them. Likewise, removing tests that reference specific environments.
2. Fixes a slight deviation between image builds in the modal-js and modal-go SDKs, where one used 2024.10 by default, and the other defaulted to empty builder version (2023.10). This caused images to be rebuilt. Also fixed empty protobuf vs `nil` field in the registry config, which changes the hash of the image.
> Test support and fix some cross-language behavior deviations

- modal-js/src/pickle.test.ts
- modal-js/src/pickle.ts
We weren't supporting signed ints. Also found that some lists use MARK op
> Fix negative ints and add MARK ops

- LICENSE
- README.md
- modal-js/package-lock.json
- modal-js/package.json
Apache 2.0 and MIT are extremely similar but matching the Python client license will make it easier to combine the repos in the future if that's something we decide to do.
> Relicense as Apache 2.0

- DEVELOPING.md
- modal-js/package.json
Trying to make the modal-js publishing workflow less risky, this splits up the version bump and the publish step so that `npm version patch` with the wrong identifier doesn't publish an invalid version.
> Split up `npm version` and `npm publish` steps

- CHANGELOG.md
- modal-go/app.go
- modal-go/client.go
- modal-go/cls.go
- modal-go/config.go
- modal-go/examples/init-client/main.go
- modal-go/function.go
- modal-go/function_call.go
- modal-go/queue.go
- modal-go/secret.go
- modal-js/examples/init-client.ts
- modal-js/src/client.ts
- modal-js/src/config.ts
- modal-js/src/index.ts
This allows you to run:
```ts
import { initializeClient } from "modal";
initializeClient({
tokenId: "ak-123123456",
tokenSecret: "as-123123123",
});
```
After startup and before calling any Modal APIs.
> Add initializeClient and do not panic at startup if missing token

- modal-js/src/function.ts
It's private on Cls, should also be private on Function
> Fix inconsistent private-ness of inputPlaneUrl

- CHANGELOG.md
- modal-js/package-lock.json
- modal-js/package.json
Release modal-js/v0.3.16, modal-go/v0.0.16, by running `python ci/release.py version patch`
Due to branch protection, this needs to be done in a PR.
> Release modal-js/v0.3.16, modal-go/v0.0.16

- ci/release.py
There was a bug in the publish script where the go release's tag did not update.
With this PR, the changelog becomes the source of truth for the go version to publish.
> Get go version from the changelog

- .github/workflows/publish.yaml
- ci/release.py
This together with https://github.com/modal-labs/libmodal/pull/80 will automate the release process. This PR adds a workflow that triggers publish when the commit message starts with "Prepare release for" which is created by https://github.com/modal-labs/libmodal/pull/80
With this PR, the release workflow becomes:
1. Trigger workflow from https://github.com/modal-labs/libmodal/pull/80 which opens a PR
2. One of us merges the PR
3. This PR's workflow runs to publish
---
For this PR to work, we also need to add a `NPM_TOKEN` sercret to auth with the npm registry.
> Add publish release workflow to trigger on message

- modal-js/test/cloud_bucket_mount.test.ts
- modal-js/vitest.config.ts
Without this alias, vitest will not pick up on src changes without `npm run build`.
> Fix test imports

- .github/workflows/docs.yaml
They [recently pinned the `upload-artifact` sub-dependency to a full SHA](https://github.com/actions/upload-pages-artifact/releases/tag/v4.0.0).
> Upgrade upload-pages-artifact GHA

- .github/workflows/release.yaml
The github action will always force push to a `ci-release` branch and open a PR from there. 
Tested it on my fork: https://github.com/thomasjpfan/libmodal/pull/6
> Use gh cli for pr workflow

- ci/release.py
I had to `curl https://proxy.golang.org` to make sure the docs in https://pkg.go.dev/github.com/modal-labs/libmodal/modal-go gets updated.
> Curl proxy.golang to make sure it picks up the update

- modal-go/test/image_test.go
These used to test deprecated functions, that have now been removed.
> Remove obsolete tests
